<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="David Villafuerte">
<meta name="dcterms.date" content="2026-08-01">
<meta name="description" content="Analizamos cómo los descuentos se relacionan con la rentabilidad utilizando regresión lineal bayesiana sobre el conjunto de datos Superstore Sales.">

<title>¿Los descuentos están reduciendo nuestras ganancias? – Business Analytics Bayesiano</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e4b63f58dceb859deda4f50e930cd0fc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Business Analytics Bayesiano</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Proyectos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">Sobre el Autor</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/jaimedavidvillafuerte/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/jaidafuerte2"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/jvillafuertemd"> <i class="bi bi-twitter-x" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#los-descuentos-están-reduciendo-nuestras-ganancias" id="toc-los-descuentos-están-reduciendo-nuestras-ganancias" class="nav-link active" data-scroll-target="#los-descuentos-están-reduciendo-nuestras-ganancias">¿Los descuentos están reduciendo nuestras ganancias?</a>
  <ul class="collapse">
  <li><a href="#la-pregunta-de-negocio" id="toc-la-pregunta-de-negocio" class="nav-link" data-scroll-target="#la-pregunta-de-negocio">La pregunta de negocio</a></li>
  </ul></li>
  <li><a href="#comprendiendo-el-problema" id="toc-comprendiendo-el-problema" class="nav-link" data-scroll-target="#comprendiendo-el-problema">Comprendiendo el problema</a></li>
  <li><a href="#explorando-los-datos" id="toc-explorando-los-datos" class="nav-link" data-scroll-target="#explorando-los-datos">Explorando los datos</a></li>
  <li><a href="#construyendo-el-modelo" id="toc-construyendo-el-modelo" class="nav-link" data-scroll-target="#construyendo-el-modelo">Construyendo el modelo</a></li>
  <li><a href="#un-primer-resumen-del-modelo" id="toc-un-primer-resumen-del-modelo" class="nav-link" data-scroll-target="#un-primer-resumen-del-modelo">Un primer resumen del modelo</a></li>
  <li><a href="#la-relación-estimada-por-el-modelo" id="toc-la-relación-estimada-por-el-modelo" class="nav-link" data-scroll-target="#la-relación-estimada-por-el-modelo">La relación estimada por el modelo</a></li>
  <li><a href="#qué-tan-segura-parece-esa-conclusión" id="toc-qué-tan-segura-parece-esa-conclusión" class="nav-link" data-scroll-target="#qué-tan-segura-parece-esa-conclusión">¿Qué tan segura parece esa conclusión?</a></li>
  <li><a href="#visualizando-la-distribución-posterior" id="toc-visualizando-la-distribución-posterior" class="nav-link" data-scroll-target="#visualizando-la-distribución-posterior">Visualizando la distribución posterior</a></li>
  <li><a href="#interpretando-los-resultados" id="toc-interpretando-los-resultados" class="nav-link" data-scroll-target="#interpretando-los-resultados">Interpretando los resultados</a></li>
  <li><a href="#recomendaciones-para-el-negocio" id="toc-recomendaciones-para-el-negocio" class="nav-link" data-scroll-target="#recomendaciones-para-el-negocio">Recomendaciones para el negocio</a></li>
  <li><a href="#limitaciones-del-análisis" id="toc-limitaciones-del-análisis" class="nav-link" data-scroll-target="#limitaciones-del-análisis">Limitaciones del análisis</a></li>
  <li><a href="#reflexión-bayesiana" id="toc-reflexión-bayesiana" class="nav-link" data-scroll-target="#reflexión-bayesiana">Reflexión bayesiana</a></li>
  <li><a href="#apéndice-código-completo" id="toc-apéndice-código-completo" class="nav-link" data-scroll-target="#apéndice-código-completo">Apéndice — Código completo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">¿Los descuentos están reduciendo nuestras ganancias?</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Retail</div>
    <div class="quarto-category">Finanzas</div>
  </div>
  </div>

<div>
  <div class="description">
    Analizamos cómo los descuentos se relacionan con la rentabilidad utilizando regresión lineal bayesiana sobre el conjunto de datos Superstore Sales.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>David Villafuerte </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="los-descuentos-están-reduciendo-nuestras-ganancias" class="level1">
<h1>¿Los descuentos están reduciendo nuestras ganancias?</h1>
<section id="la-pregunta-de-negocio" class="level2">
<h2 class="anchored" data-anchor-id="la-pregunta-de-negocio">La pregunta de negocio</h2>
<p>Los descuentos forman parte de la estrategia comercial de prácticamente todas las empresas de retail. Reducir temporalmente el precio de un producto puede atraer nuevos clientes, aumentar el volumen de ventas y acelerar la rotación del inventario.</p>
<p>Sin embargo, vender más no siempre significa ganar más.</p>
<p>Cada descuento reduce el ingreso obtenido por una venta y, si no se compensa con un mayor volumen o con otros beneficios estratégicos, puede terminar disminuyendo la rentabilidad del negocio.</p>
<p>En este proyecto analizaremos precisamente esa relación utilizando información del conjunto de datos <strong>Superstore Sales</strong>.</p>
<p>La pregunta que intentaremos responder es sencilla:</p>
<blockquote class="blockquote">
<p><strong>¿Hasta qué punto los descuentos parecen afectar las ganancias obtenidas por la empresa?</strong></p>
</blockquote>
<p>Nuestro objetivo no consiste en demostrar una relación causal entre ambas variables. Trabajamos con datos observacionales y existen muchos otros factores que también pueden influir sobre la utilidad de una venta.</p>
<p>Lo que buscamos es estimar cuál parece ser la tendencia general y cuánta incertidumbre existe alrededor de esa estimación.</p>
<hr>
</section>
</section>
<section id="comprendiendo-el-problema" class="level1">
<h1>Comprendiendo el problema</h1>
<p>Trabajaremos únicamente con dos variables.</p>
<ul>
<li><strong>Profit:</strong> utilidad obtenida en cada venta.</li>
<li><strong>Discount:</strong> descuento aplicado al cliente, expresado como una proporción entre 0 y 1.</li>
</ul>
<p>Por ejemplo:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Descuento</th>
<th style="text-align: left;">Interpretación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.00</td>
<td style="text-align: left;">Sin descuento</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.20</td>
<td style="text-align: left;">20 % de descuento</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.50</td>
<td style="text-align: left;">50 % de descuento</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.80</td>
<td style="text-align: left;">80 % de descuento</td>
</tr>
</tbody>
</table>
<p>Intuitivamente podríamos esperar que descuentos más altos reduzcan las ganancias.</p>
<p>No obstante, esa relación no siempre es evidente. Un descuento puede estimular las ventas de productos con márgenes elevados, facilitar la salida de inventario o atraer nuevos clientes que posteriormente realicen compras adicionales.</p>
<p>Antes de construir cualquier modelo conviene explorar visualmente los datos.</p>
<hr>
</section>
<section id="explorando-los-datos" class="level1">
<h1>Explorando los datos</h1>
<p>Comenzaremos observando cómo se distribuyen las ganancias registradas en las ventas del supermercado.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La mayor parte de las ventas presentan ganancias cercanas a cero. En el histograma se observa un pico muy pronunciado alrededor de ese valor, con cerca de <strong>9 000 ventas</strong> concentradas en esa zona.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Al ampliar la escala vertical se aprecia que las ganancias superiores a <strong>2 500 dólares</strong> y las pérdidas inferiores a <strong>−2 500 dólares</strong> son mucho menos frecuentes, generalmente con menos de un centenar de observaciones. Más allá de esos valores todavía existen casos extremos, con pérdidas cercanas a <strong>−5 000 dólares</strong> y ganancias superiores a <strong>5 000 dólares</strong>, aunque representan una fracción muy pequeña del total.</p>
<p>En conjunto, este gráfico muestra que la mayoría de las operaciones generan utilidades relativamente moderadas, mientras que las ganancias y pérdidas muy grandes son eventos poco frecuentes.</p>
<hr>
<p>Ahora observaremos cómo se distribuyen los descuentos aplicados.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La política comercial de la empresa no distribuye los descuentos de manera uniforme.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(superstore,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> Discount)) <span class="sc">+</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">bins =</span> <span class="dv">20</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"#41AE76"</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"white"</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribución de los descuentos"</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Descuento"</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Número de ventas"</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El descuento más frecuente es <strong>0 %</strong>, con más de <strong>4 500 ventas</strong>, seguido por el <strong>20 %</strong>, que aparece en más de <strong>3 500 operaciones</strong>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(superstore,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> Discount)) <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">bins =</span> <span class="dv">20</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"#41AE76"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"white"</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">500</span>)) <span class="sc">+</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribución de los descuentos"</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Discount"</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Número de ventas"</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Al ampliar la escala también se observa que los descuentos del <strong>70 %</strong> y <strong>80 %</strong> son considerablemente menos frecuentes, con aproximadamente <strong>400</strong> y <strong>300 ventas</strong>, respectivamente. Los descuentos del <strong>30 %</strong> y <strong>40 %</strong> aparecen en cerca de <strong>200 operaciones</strong> cada uno.</p>
<p>Este patrón indica que la empresa concentra la mayor parte de sus ventas en pocos niveles de descuento, mientras que los descuentos más agresivos se utilizan únicamente en una proporción reducida de transacciones.</p>
<hr>
<p>Finalmente exploraremos la relación entre ambas variables.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El diagrama de dispersión revela un patrón que resulta difícil apreciar observando cada variable por separado.</p>
<p>Cuando los descuentos son inferiores al <strong>20 %</strong>, predominan las ventas con ganancias positivas y las pérdidas son relativamente escasas.</p>
<p>Alrededor del <strong>20 %</strong> comienza a observarse un equilibrio entre operaciones rentables y operaciones con pérdidas.</p>
<p>A partir del <strong>30 %</strong> de descuento la nube de puntos muestra una mayor concentración de pérdidas que de ganancias, lo que sugiere una posible asociación negativa entre el descuento aplicado y la utilidad obtenida.</p>
<p>Naturalmente, este gráfico no demuestra que los descuentos provoquen esas pérdidas. Sin embargo, sí proporciona una primera evidencia visual de que ambas variables podrían estar relacionadas y justifica la construcción de un modelo bayesiano para cuantificar esa tendencia.</p>
<hr>
</section>
<section id="construyendo-el-modelo" class="level1">
<h1>Construyendo el modelo</h1>
<p>El gráfico de dispersión sugiere que las ganancias tienden a disminuir conforme aumentan los descuentos. Sin embargo, una inspección visual no permite cuantificar esa relación ni evaluar la incertidumbre que la acompaña.</p>
<p>Para responder con mayor rigor nuestra pregunta de negocio construiremos un modelo de <strong>regresión lineal bayesiana</strong> utilizando <strong>rstanarm</strong>.</p>
<p>En este modelo la utilidad (<code>Profit</code>) será la variable respuesta y el descuento (<code>Discount</code>) actuará como variable explicativa.</p>
<p>A diferencia de una regresión clásica, el modelo bayesiano no estima una única recta considerada como la “verdadera”.</p>
<p>En su lugar, calcula una distribución de rectas plausibles compatibles con la evidencia disponible.</p>
<p>Esta diferencia es importante porque nuestro objetivo no consiste en encontrar una respuesta absoluta, sino en describir qué escenarios reciben mayor apoyo por parte de los datos.</p>
<hr>
</section>
<section id="un-primer-resumen-del-modelo" class="level1">
<h1>Un primer resumen del modelo</h1>
<p>Antes de construir nuevas visualizaciones podemos revisar los parámetros principales estimados por el modelo.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Parámetro</th>
<th style="text-align: right;">Mediana posterior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercepto</td>
<td style="text-align: right;">67.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Discount</td>
<td style="text-align: right;">−249.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sigma</td>
<td style="text-align: right;">228.5</td>
</tr>
</tbody>
</table>
<p>La interpretación de estos parámetros es relativamente sencilla.</p>
<p>Cuando no se aplica ningún descuento (<code>Discount = 0</code>), la utilidad media estimada es de aproximadamente <strong>67.7 dólares</strong> por venta.</p>
<p>Por otra parte, el coeficiente asociado al descuento presenta una mediana posterior de <strong>−249.6</strong>.</p>
<p>Como la variable <code>Discount</code> está expresada entre <strong>0 y 1</strong>, este valor representa el cambio esperado en la utilidad al pasar, hipotéticamente, de <strong>0 % a 100 % de descuento</strong>.</p>
<p>En la práctica nunca observaremos un cambio tan extremo, pero el signo negativo del coeficiente ya sugiere una relación inversa entre ambas variables: conforme aumentan los descuentos, la utilidad esperada tiende a disminuir.</p>
<p>Finalmente, el parámetro <strong>sigma</strong> se estima alrededor de <strong>228.5 dólares</strong>.</p>
<p>Este valor resume la variabilidad de las ganancias que el modelo no consigue explicar únicamente mediante el descuento. En otras palabras, existen muchos otros factores que probablemente influyen sobre la rentabilidad de una venta.</p>
<hr>
</section>
<section id="la-relación-estimada-por-el-modelo" class="level1">
<h1>La relación estimada por el modelo</h1>
<p>Aunque los coeficientes son informativos, resulta mucho más sencillo comprender el comportamiento del modelo mediante una representación gráfica.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ahora la tendencia observada en el gráfico exploratorio queda cuantificada por el modelo bayesiano.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Haciendo un acercamiento observamos que la línea central representa la utilidad media esperada para cada nivel de descuento, mientras que la banda azul resume el rango de valores más plausibles para esa media.</p>
<p>La pendiente negativa resulta evidente.</p>
<p>Cuando no se aplican descuentos, el modelo estima ganancias cercanas a <strong>70 dólares</strong> por venta.</p>
<p>A medida que el descuento aumenta, la utilidad esperada disminuye de forma prácticamente lineal. Con descuentos cercanos al <strong>80 %</strong>, la tendencia estimada alcanza aproximadamente <strong>130 dólares de pérdida</strong> por venta.</p>
<p>Un aspecto especialmente interesante es el punto donde la línea cruza el valor cero.</p>
<p>Según la tendencia estimada, esto ocurre alrededor de un <strong>30 % de descuento</strong>. A partir de ese nivel, el escenario más plausible deja de ser una utilidad positiva y pasa a ser una pérdida promedio.</p>
<p>Naturalmente, esto no significa que todas las ventas con descuentos superiores al 30 % generen pérdidas. La nube de puntos continúa mostrando una gran variabilidad. Sin embargo, la evidencia disponible sugiere que, en promedio, descuentos cada vez mayores se asocian con una disminución progresiva de la rentabilidad.</p>
<hr>
</section>
<section id="qué-tan-segura-parece-esa-conclusión" class="level1">
<h1>¿Qué tan segura parece esa conclusión?</h1>
<p>Hasta ahora hemos descrito la tendencia promedio.</p>
<p>Sin embargo, uno de los principales beneficios del enfoque bayesiano consiste en que también permite cuantificar la incertidumbre asociada a esa estimación.</p>
<p>Para ello analizaremos el intervalo posterior y la distribución posterior del coeficiente correspondiente al descuento.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5%      97.5%
(Intercept)   62.03286   73.10062
Discount    -270.25999 -226.60977
sigma        225.27095  231.69106</code></pre>
</div>
</div>
<p>El intervalo posterior del <strong>95 %</strong> para el coeficiente del descuento se extiende aproximadamente desde <strong>−270.3</strong> hasta <strong>−226.6</strong>.</p>
<p>Todo el intervalo permanece por debajo de cero.</p>
<p>Esto significa que, dadas las observaciones disponibles y el modelo utilizado, los escenarios más plausibles son compatibles con un efecto negativo del descuento sobre las ganancias.</p>
<p>En otras palabras, la evidencia disponible sugiere de manera consistente que descuentos mayores se asocian con una menor utilidad promedio.</p>
<p>Todavía no sabemos exactamente cuál es el valor “verdadero” del efecto.</p>
<p>Lo que sí sabemos es que, dentro del rango de valores más plausibles considerado por el modelo, todos describen una asociación negativa entre ambas variables.</p>
<hr>
</section>
<section id="visualizando-la-distribución-posterior" class="level1">
<h1>Visualizando la distribución posterior</h1>
<p>El intervalo resume la incertidumbre mediante dos números.</p>
<p>La distribución posterior permite observar esa incertidumbre de forma mucho más intuitiva.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La distribución posterior se encuentra claramente concentrada alrededor de <strong>−250</strong>, que coincide con la mediana estimada por el modelo.</p>
<p>La franja azul más oscura representa el <strong>80 %</strong> central de los valores posteriores y se extiende aproximadamente desde <strong>−265</strong> hasta <strong>−235</strong>.</p>
<p>La franja azul más clara amplía ese rango hasta el <strong>95 %</strong> central, alcanzando aproximadamente valores entre <strong>−270</strong> y <strong>−226</strong>.</p>
<p>Una característica importante de esta figura es que prácticamente toda la distribución permanece por debajo de cero.</p>
<p>Esto proporciona una representación visual muy clara de la evidencia obtenida: los escenarios compatibles con un efecto positivo del descuento sobre las ganancias reciben muy poco apoyo por parte de los datos.</p>
<hr>
</section>
<section id="interpretando-los-resultados" class="level1">
<h1>Interpretando los resultados</h1>
<p>Nuestro objetivo nunca fue encontrar una ecuación perfecta para describir las ganancias de la empresa.</p>
<p>La verdadera pregunta siempre fue otra:</p>
<blockquote class="blockquote">
<p><strong>¿Qué nos sugieren los datos acerca de la relación entre los descuentos y la rentabilidad?</strong></p>
</blockquote>
<p>La evidencia obtenida mediante el modelo bayesiano apunta en una dirección bastante consistente.</p>
<p>Por una parte, la recta de regresión muestra una tendencia descendente a medida que aumenta el descuento aplicado a las ventas.</p>
<p>Por otra, tanto el intervalo posterior como la distribución posterior del coeficiente permanecen completamente por debajo de cero.</p>
<p>En conjunto, estos resultados sugieren que <strong>descuentos mayores se asocian con menores ganancias promedio</strong>.</p>
<p>El modelo estima una utilidad cercana a <strong>68 dólares</strong> cuando no se aplica ningún descuento y una disminución esperada de aproximadamente <strong>250 dólares</strong> al recorrer toda la escala del descuento, desde <strong>0 % hasta 100 %</strong>.</p>
<p>Naturalmente, ninguna empresa aplica descuentos del 100 % de manera habitual. Sin embargo, este coeficiente resume la intensidad de la relación observada entre ambas variables y permite comprender claramente su dirección.</p>
<p>La evidencia también muestra que el descuento no explica completamente el comportamiento de las ganancias.</p>
<p>El valor estimado de <strong>sigma (228.5 dólares)</strong> indica que continúa existiendo una variabilidad considerable que probablemente depende de otros factores presentes en el negocio.</p>
<p>Entre ellos podrían encontrarse la categoría del producto, el segmento del cliente, la región geográfica, la cantidad vendida o incluso la combinación de varios de estos elementos.</p>
<p>Este resultado constituye un recordatorio importante.</p>
<p>Los descuentos parecen formar parte de la explicación del problema, pero no representan toda la historia.</p>
<hr>
</section>
<section id="recomendaciones-para-el-negocio" class="level1">
<h1>Recomendaciones para el negocio</h1>
<p>Desde la perspectiva de Business Analytics, el objetivo de este análisis no consiste en eliminar los descuentos.</p>
<p>Los descuentos continúan siendo una herramienta comercial valiosa cuando ayudan a atraer nuevos clientes, aumentar el volumen de ventas o reducir inventarios.</p>
<p>Sin embargo, la evidencia disponible sugiere que su utilización debe planificarse cuidadosamente.</p>
<p>En particular, los resultados invitan a considerar las siguientes acciones.</p>
<ul>
<li><p>Revisar periódicamente la política de descuentos para identificar si existen niveles a partir de los cuales la utilidad comienza a deteriorarse de forma sistemática.</p></li>
<li><p>Analizar por separado las distintas categorías de productos, ya que algunos podrían soportar descuentos elevados sin afectar significativamente la rentabilidad, mientras que otros podrían generar pérdidas incluso con reducciones moderadas del precio.</p></li>
<li><p>Complementar este análisis incorporando nuevas variables que permitan comprender mejor las diferencias observadas entre unas ventas y otras.</p></li>
</ul>
<p>Más que establecer una regla rígida sobre qué porcentaje de descuento utilizar, este estudio proporciona una base objetiva para iniciar una conversación apoyada en evidencia.</p>
<hr>
</section>
<section id="limitaciones-del-análisis" class="level1">
<h1>Limitaciones del análisis</h1>
<p>Como ocurre en cualquier proyecto de análisis de datos, estos resultados deben interpretarse dentro del contexto del modelo utilizado.</p>
<p>En primer lugar, únicamente analizamos la relación entre dos variables: las ganancias y el descuento.</p>
<p>Esto significa que otros factores potencialmente relevantes permanecen fuera del modelo.</p>
<p>En segundo lugar, trabajamos con datos observacionales.</p>
<p>Por esa razón, los resultados describen asociaciones compatibles con la evidencia disponible, pero no permiten afirmar que los descuentos sean la causa directa de las pérdidas observadas.</p>
<p>Finalmente, el modelo supone una relación lineal promedio entre ambas variables.</p>
<p>Es posible que en algunos segmentos del negocio la relación real sea más compleja y requiera modelos con múltiples predictores o estructuras más flexibles.</p>
<p>Lejos de representar una debilidad, estas limitaciones señalan el camino para profundizar el análisis en futuras publicaciones.</p>
<hr>
</section>
<section id="reflexión-bayesiana" class="level1">
<h1>Reflexión bayesiana</h1>
<p>Uno de los mayores aportes del enfoque bayesiano consiste en cambiar la forma en que interpretamos la evidencia.</p>
<p>En lugar de buscar respuestas absolutas, aprendemos a trabajar con escenarios plausibles y con distintos grados de incertidumbre.</p>
<p>En este proyecto no intentamos demostrar que los descuentos sean buenos o malos.</p>
<p>Lo que hicimos fue cuantificar qué escenarios parecen más compatibles con la información disponible y reconocer, al mismo tiempo, que todavía existen aspectos importantes que nuestro modelo no explica.</p>
<p>Esa es precisamente la fortaleza del razonamiento bayesiano.</p>
<p>No elimina la incertidumbre.</p>
<p>La incorpora explícitamente dentro del proceso de toma de decisiones.</p>
<p>En el próximo artículo ampliaremos este análisis incorporando nuevos factores que también podrían influir sobre la rentabilidad.</p>
<p>De esta manera iremos construyendo modelos cada vez más útiles para comprender el funcionamiento del negocio sin perder de vista que toda decisión continúa realizándose bajo incertidumbre.</p>
<hr>
</section>
<section id="apéndice-código-completo" class="level1">
<h1>Apéndice — Código completo</h1>
<p>El siguiente código reproduce cronológicamente todo el análisis presentado en este artículo.</p>
<p>Los bloques utilizan <code>eval: false</code> para evitar una segunda ejecución durante el renderizado y facilitar que el lector pueda copiar cada paso del análisis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rstanarm)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(posterior)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(bayesplot)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Exploración inicial</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(superstore,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> Profit)) <span class="sc">+</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">bins =</span> <span class="dv">40</span>,</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"#2C7FB8"</span>,</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"white"</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(superstore,</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> Discount)) <span class="sc">+</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">bins =</span> <span class="dv">20</span>,</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"#41AE76"</span>,</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"white"</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(superstore,</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> Discount,</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> Profit</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>       )) <span class="sc">+</span></span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.20</span>)</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo bayesiano</span></span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>modelo_profit <span class="ot">&lt;-</span> <span class="fu">stan_glm</span>(</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>  Profit <span class="sc">~</span> Discount,</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> superstore,</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">gaussian</span>(),</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>  <span class="at">chains =</span> <span class="dv">2</span>,</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>  <span class="at">iter =</span> <span class="dv">1000</span>,</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed =</span> <span class="dv">1234</span>,</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a>  <span class="at">refresh =</span> <span class="dv">0</span></span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a><span class="co"># Predicciones posteriores</span></span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a>nuevo <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a>  <span class="at">Discount =</span> <span class="fu">seq</span>(</span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a>    <span class="fu">min</span>(superstore<span class="sc">$</span>Discount),</span>
<span id="cb4-49"><a href="#cb4-49" aria-hidden="true" tabindex="-1"></a>    <span class="fu">max</span>(superstore<span class="sc">$</span>Discount),</span>
<span id="cb4-50"><a href="#cb4-50" aria-hidden="true" tabindex="-1"></a>    <span class="at">length.out =</span> <span class="dv">100</span></span>
<span id="cb4-51"><a href="#cb4-51" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-52"><a href="#cb4-52" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-53"><a href="#cb4-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-54"><a href="#cb4-54" aria-hidden="true" tabindex="-1"></a>pred_media <span class="ot">&lt;-</span> <span class="fu">posterior_linpred</span>(</span>
<span id="cb4-55"><a href="#cb4-55" aria-hidden="true" tabindex="-1"></a>  modelo_profit,</span>
<span id="cb4-56"><a href="#cb4-56" aria-hidden="true" tabindex="-1"></a>  <span class="at">newdata =</span> nuevo</span>
<span id="cb4-57"><a href="#cb4-57" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-58"><a href="#cb4-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-59"><a href="#cb4-59" aria-hidden="true" tabindex="-1"></a>nuevo <span class="ot">&lt;-</span> nuevo <span class="sc">|&gt;</span></span>
<span id="cb4-60"><a href="#cb4-60" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-61"><a href="#cb4-61" aria-hidden="true" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">apply</span>(pred_media, <span class="dv">2</span>, median),</span>
<span id="cb4-62"><a href="#cb4-62" aria-hidden="true" tabindex="-1"></a>    <span class="at">li =</span> <span class="fu">apply</span>(pred_media, <span class="dv">2</span>, quantile, <span class="at">probs =</span> <span class="fl">0.05</span>),</span>
<span id="cb4-63"><a href="#cb4-63" aria-hidden="true" tabindex="-1"></a>    <span class="at">ls =</span> <span class="fu">apply</span>(pred_media, <span class="dv">2</span>, quantile, <span class="at">probs =</span> <span class="fl">0.95</span>)</span>
<span id="cb4-64"><a href="#cb4-64" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-65"><a href="#cb4-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-66"><a href="#cb4-66" aria-hidden="true" tabindex="-1"></a><span class="co"># Recta bayesiana</span></span>
<span id="cb4-67"><a href="#cb4-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-68"><a href="#cb4-68" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(superstore,</span>
<span id="cb4-69"><a href="#cb4-69" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(</span>
<span id="cb4-70"><a href="#cb4-70" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> Discount,</span>
<span id="cb4-71"><a href="#cb4-71" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> Profit</span>
<span id="cb4-72"><a href="#cb4-72" aria-hidden="true" tabindex="-1"></a>       )) <span class="sc">+</span></span>
<span id="cb4-73"><a href="#cb4-73" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.20</span>) <span class="sc">+</span></span>
<span id="cb4-74"><a href="#cb4-74" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(</span>
<span id="cb4-75"><a href="#cb4-75" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> nuevo,</span>
<span id="cb4-76"><a href="#cb4-76" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(</span>
<span id="cb4-77"><a href="#cb4-77" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> Discount,</span>
<span id="cb4-78"><a href="#cb4-78" aria-hidden="true" tabindex="-1"></a>      <span class="at">ymin =</span> li,</span>
<span id="cb4-79"><a href="#cb4-79" aria-hidden="true" tabindex="-1"></a>      <span class="at">ymax =</span> ls</span>
<span id="cb4-80"><a href="#cb4-80" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb4-81"><a href="#cb4-81" aria-hidden="true" tabindex="-1"></a>    <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>,</span>
<span id="cb4-82"><a href="#cb4-82" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.20</span></span>
<span id="cb4-83"><a href="#cb4-83" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb4-84"><a href="#cb4-84" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(</span>
<span id="cb4-85"><a href="#cb4-85" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> nuevo,</span>
<span id="cb4-86"><a href="#cb4-86" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(</span>
<span id="cb4-87"><a href="#cb4-87" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> Discount,</span>
<span id="cb4-88"><a href="#cb4-88" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> media</span>
<span id="cb4-89"><a href="#cb4-89" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb4-90"><a href="#cb4-90" aria-hidden="true" tabindex="-1"></a>    <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>,</span>
<span id="cb4-91"><a href="#cb4-91" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="dv">1</span></span>
<span id="cb4-92"><a href="#cb4-92" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-93"><a href="#cb4-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-94"><a href="#cb4-94" aria-hidden="true" tabindex="-1"></a><span class="co"># Intervalo posterior</span></span>
<span id="cb4-95"><a href="#cb4-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-96"><a href="#cb4-96" aria-hidden="true" tabindex="-1"></a><span class="fu">posterior_interval</span>(</span>
<span id="cb4-97"><a href="#cb4-97" aria-hidden="true" tabindex="-1"></a>  modelo_profit,</span>
<span id="cb4-98"><a href="#cb4-98" aria-hidden="true" tabindex="-1"></a>  <span class="at">prob =</span> <span class="fl">0.95</span></span>
<span id="cb4-99"><a href="#cb4-99" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-100"><a href="#cb4-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-101"><a href="#cb4-101" aria-hidden="true" tabindex="-1"></a><span class="co"># Distribución posterior</span></span>
<span id="cb4-102"><a href="#cb4-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-103"><a href="#cb4-103" aria-hidden="true" tabindex="-1"></a><span class="fu">mcmc_areas</span>(</span>
<span id="cb4-104"><a href="#cb4-104" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.matrix</span>(modelo_profit),</span>
<span id="cb4-105"><a href="#cb4-105" aria-hidden="true" tabindex="-1"></a>  <span class="at">pars =</span> <span class="st">"Discount"</span>,</span>
<span id="cb4-106"><a href="#cb4-106" aria-hidden="true" tabindex="-1"></a>  <span class="at">prob =</span> <span class="fl">0.80</span>,</span>
<span id="cb4-107"><a href="#cb4-107" aria-hidden="true" tabindex="-1"></a>  <span class="at">prob_outer =</span> <span class="fl">0.95</span></span>
<span id="cb4-108"><a href="#cb4-108" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-109"><a href="#cb4-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-110"><a href="#cb4-110" aria-hidden="true" tabindex="-1"></a><span class="co"># Resumen de coeficientes</span></span>
<span id="cb4-111"><a href="#cb4-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-112"><a href="#cb4-112" aria-hidden="true" tabindex="-1"></a>coeficientes <span class="ot">&lt;-</span> <span class="fu">as_draws_df</span>(modelo_profit) <span class="sc">|&gt;</span></span>
<span id="cb4-113"><a href="#cb4-113" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb4-114"><a href="#cb4-114" aria-hidden="true" tabindex="-1"></a>    <span class="at">Intercepto =</span> <span class="fu">median</span>(<span class="st">`</span><span class="at">(Intercept)</span><span class="st">`</span>),</span>
<span id="cb4-115"><a href="#cb4-115" aria-hidden="true" tabindex="-1"></a>    <span class="at">Descuento =</span> <span class="fu">median</span>(Discount),</span>
<span id="cb4-116"><a href="#cb4-116" aria-hidden="true" tabindex="-1"></a>    <span class="at">Sigma =</span> <span class="fu">median</span>(sigma)</span>
<span id="cb4-117"><a href="#cb4-117" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-118"><a href="#cb4-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-119"><a href="#cb4-119" aria-hidden="true" tabindex="-1"></a>coeficientes <span class="sc">|&gt;</span></span>
<span id="cb4-120"><a href="#cb4-120" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb4-121"><a href="#cb4-121" aria-hidden="true" tabindex="-1"></a>    <span class="fu">everything</span>(),</span>
<span id="cb4-122"><a href="#cb4-122" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"Parametro"</span>,</span>
<span id="cb4-123"><a href="#cb4-123" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"Mediana"</span></span>
<span id="cb4-124"><a href="#cb4-124" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb4-125"><a href="#cb4-125" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gt</span>() <span class="sc">|&gt;</span></span>
<span id="cb4-126"><a href="#cb4-126" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fmt_number</span>(</span>
<span id="cb4-127"><a href="#cb4-127" aria-hidden="true" tabindex="-1"></a>    <span class="at">columns =</span> Mediana,</span>
<span id="cb4-128"><a href="#cb4-128" aria-hidden="true" tabindex="-1"></a>    <span class="at">decimals =</span> <span class="dv">2</span></span>
<span id="cb4-129"><a href="#cb4-129" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>