<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="David Villafuerte">
<meta name="dcterms.date" content="2026-09-03">
<meta name="description" content="Un pronóstico bayesiano de las ventas de Superstore para aprender a planificar el próximo mes considerando la incertidumbre.">

<title>¿Cómo planificar las ventas del próximo mes sin asumir que conocemos el futuro? – Business Analytics Bayesiano</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e4b63f58dceb859deda4f50e930cd0fc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Business Analytics Bayesiano</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Proyectos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">Sobre el Autor</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/jaimedavidvillafuerte/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/jaidafuerte2"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/jvillafuertemd"> <i class="bi bi-twitter-x" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#la-pregunta-de-negocio" id="toc-la-pregunta-de-negocio" class="nav-link active" data-scroll-target="#la-pregunta-de-negocio">1. La pregunta de negocio</a></li>
  <li><a href="#comprender-el-problema" id="toc-comprender-el-problema" class="nav-link" data-scroll-target="#comprender-el-problema">2. Comprender el problema</a></li>
  <li><a href="#de-miles-de-transacciones-a-una-serie-mensual" id="toc-de-miles-de-transacciones-a-una-serie-mensual" class="nav-link" data-scroll-target="#de-miles-de-transacciones-a-una-serie-mensual">3. De miles de transacciones a una serie mensual</a>
  <ul class="collapse">
  <li><a href="#qué-nos-dicen-los-datos" id="toc-qué-nos-dicen-los-datos" class="nav-link" data-scroll-target="#qué-nos-dicen-los-datos">¿Qué nos dicen los datos?</a></li>
  </ul></li>
  <li><a href="#construir-un-modelo-temporal-sencillo" id="toc-construir-un-modelo-temporal-sencillo" class="nav-link" data-scroll-target="#construir-un-modelo-temporal-sencillo">4. Construir un modelo temporal sencillo</a>
  <ul class="collapse">
  <li><a href="#el-punto-de-partida" id="toc-el-punto-de-partida" class="nav-link" data-scroll-target="#el-punto-de-partida">El punto de partida</a></li>
  <li><a href="#el-efecto-del-tiempo" id="toc-el-efecto-del-tiempo" class="nav-link" data-scroll-target="#el-efecto-del-tiempo">El efecto del tiempo</a></li>
  <li><a href="#qué-representa-sigma" id="toc-qué-representa-sigma" class="nav-link" data-scroll-target="#qué-representa-sigma">¿Qué representa sigma?</a></li>
  </ul></li>
  <li><a href="#qué-podría-ocurrir-el-próximo-mes" id="toc-qué-podría-ocurrir-el-próximo-mes" class="nav-link" data-scroll-target="#qué-podría-ocurrir-el-próximo-mes">5. ¿Qué podría ocurrir el próximo mes?</a></li>
  <li><a href="#el-futuro-como-una-distribución-de-escenarios" id="toc-el-futuro-como-una-distribución-de-escenarios" class="nav-link" data-scroll-target="#el-futuro-como-una-distribución-de-escenarios">6. El futuro como una distribución de escenarios</a>
  <ul class="collapse">
  <li><a href="#puede-una-empresa-tener-ventas-negativas" id="toc-puede-una-empresa-tener-ventas-negativas" class="nav-link" data-scroll-target="#puede-una-empresa-tener-ventas-negativas">¿Puede una empresa tener ventas negativas?</a></li>
  </ul></li>
  <li><a href="#el-intervalo-predictivo-cuánto-podría-variar-el-futuro" id="toc-el-intervalo-predictivo-cuánto-podría-variar-el-futuro" class="nav-link" data-scroll-target="#el-intervalo-predictivo-cuánto-podría-variar-el-futuro">7. El intervalo predictivo: cuánto podría variar el futuro</a></li>
  <li><a href="#el-pronóstico-junto-a-la-historia" id="toc-el-pronóstico-junto-a-la-historia" class="nav-link" data-scroll-target="#el-pronóstico-junto-a-la-historia">8. El pronóstico junto a la historia</a></li>
  <li><a href="#qué-decisión-empresarial-podemos-tomar" id="toc-qué-decisión-empresarial-podemos-tomar" class="nav-link" data-scroll-target="#qué-decisión-empresarial-podemos-tomar">9. ¿Qué decisión empresarial podemos tomar?</a></li>
  <li><a href="#una-reflexión-bayesiana" id="toc-una-reflexión-bayesiana" class="nav-link" data-scroll-target="#una-reflexión-bayesiana">10. Una reflexión bayesiana</a>
  <ul class="collapse">
  <li><a href="#la-idea-que-debemos-conservar" id="toc-la-idea-que-debemos-conservar" class="nav-link" data-scroll-target="#la-idea-que-debemos-conservar">La idea que debemos conservar</a></li>
  </ul></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones">11. Conclusiones</a></li>
  <li><a href="#apéndice-código-completo" id="toc-apéndice-código-completo" class="nav-link" data-scroll-target="#apéndice-código-completo">Apéndice — Código completo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">¿Cómo planificar las ventas del próximo mes sin asumir que conocemos el futuro?</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Retail</div>
    <div class="quarto-category">Forecasting</div>
    <div class="quarto-category">Finanzas</div>
  </div>
  </div>

<div>
  <div class="description">
    Un pronóstico bayesiano de las ventas de Superstore para aprender a planificar el próximo mes considerando la incertidumbre.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>David Villafuerte </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 3, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="la-pregunta-de-negocio" class="level1">
<h1>1. La pregunta de negocio</h1>
<p>Cuando una empresa planifica el próximo mes necesita tomar decisiones antes de conocer lo que realmente ocurrirá.</p>
<p>¿Cuánto inventario debemos preparar? ¿Cuántas personas necesitaremos? ¿Cuánto dinero podríamos necesitar para operar? ¿Qué nivel de ventas sería razonable utilizar como referencia?</p>
<p>Una respuesta tradicional podría consistir en calcular un único valor y utilizarlo como pronóstico.</p>
<p>Pero el futuro no funciona de esa manera.</p>
<p>Aunque podamos encontrar patrones en los datos históricos, siempre existe incertidumbre. Por eso, en lugar de preguntar únicamente:</p>
<blockquote class="blockquote">
<p><strong>¿Cuánto venderemos el próximo mes?</strong></p>
</blockquote>
<p>podemos plantear una pregunta más útil:</p>
<blockquote class="blockquote">
<p><strong>¿Qué valores de ventas son plausibles para el próximo mes y qué tan incierto es ese escenario?</strong></p>
</blockquote>
<p>Esta diferencia es fundamental para el análisis de negocios.</p>
<p>En esta entrada utilizaremos los datos de <strong>Superstore Sales</strong> para construir un modelo bayesiano sencillo que relacione las ventas mensuales con el paso del tiempo y nos permita generar una distribución de posibles ventas para el mes siguiente.</p>
<p>El objetivo no será adivinar el futuro.</p>
<p>Será <strong>cuantificar nuestra incertidumbre sobre él</strong>.</p>
</section>
<section id="comprender-el-problema" class="level1">
<h1>2. Comprender el problema</h1>
<p>Nuestro conjunto de datos contiene 9.994 registros de ventas y diferentes variables relacionadas con pedidos, clientes, productos y resultados comerciales.</p>
<p>Para este análisis nos interesan principalmente dos variables:</p>
<ul>
<li><code>Order Date</code>: fecha de la venta.</li>
<li><code>Sales</code>: valor de la venta.</li>
</ul>
<p>Antes de construir cualquier modelo temporal necesitamos comprobar cómo están almacenadas realmente las fechas. Y vemos que están almacenadas como cadenas de caracteres:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(superstore<span class="sc">$</span><span class="st">`</span><span class="at">Order ID</span><span class="st">`</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"</code></pre>
</div>
</div>
<p>Esto es importante porque una fecha almacenada como texto no puede utilizarse directamente como una variable temporal. Entonces transformamos el texto a formato de fecha</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>superstore <span class="ot">&lt;-</span> superstore <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Order_Date =</span> <span class="fu">mdy</span>(<span class="st">`</span><span class="at">Order Date</span><span class="st">`</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Y comprobamos resumiendo la variable de fecha de pedido:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(superstore<span class="sc">$</span>Order_Date)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Min.      1st Qu.       Median         Mean      3rd Qu.         Max. 
"2014-01-03" "2015-05-23" "2016-06-26" "2016-04-30" "2017-05-14" "2017-12-30" </code></pre>
</div>
</div>
<p>Y también deberíamos asegurarnos de no tener valores faltantes:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(superstore<span class="sc">$</span>Order_Date))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>La variable <code>Order Date</code> estaba almacenada como texto, pero sus valores tenían el formato mes/día/año. Por ello utilizamos <code>mdy()</code> para convertirla correctamente a una fecha.</p>
<p>El resultado confirma que la transformación funcionó.</p>
<p>La primera fecha observada es el <strong>3 de enero de 2014</strong> y la última es el <strong>30 de diciembre de 2017</strong>. Además, no se encontraron valores faltantes después de la transformación.</p>
<p>Tenemos, por tanto, un período de aproximadamente cuatro años sobre el cual podemos observar la evolución de las ventas.</p>
</section>
<section id="de-miles-de-transacciones-a-una-serie-mensual" class="level1">
<h1>3. De miles de transacciones a una serie mensual</h1>
<p>El dataset original contiene cada operación individual. Para estudiar la evolución temporal de las ventas necesitamos cambiar el nivel de análisis.</p>
<p>En lugar de analizar cada pedido, vamos a sumar todas las ventas correspondientes a cada mes.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 48 × 2
   Mes         Sales
   &lt;date&gt;      &lt;dbl&gt;
 1 2014-01-01 14237.
 2 2014-02-01  4520.
 3 2014-03-01 55691.
 4 2014-04-01 28295.
 5 2014-05-01 23648.
 6 2014-06-01 34595.
 7 2014-07-01 33946.
 8 2014-08-01 27909.
 9 2014-09-01 81777.
10 2014-10-01 31453.
# ℹ 38 more rows</code></pre>
</div>
</div>
<p>El resultado contiene <strong>48 observaciones mensuales</strong>, desde enero de 2014 hasta diciembre de 2017.</p>
<p>Por ejemplo, las ventas fueron de aproximadamente 14.237 dólares en enero de 2014 y alcanzaron aproximadamente 118.448 dólares en noviembre de 2017.</p>
<p>Esta transformación es importante porque ahora tenemos una verdadera serie temporal mensual.</p>
<section id="qué-nos-dicen-los-datos" class="level2">
<h2 class="anchored" data-anchor-id="qué-nos-dicen-los-datos">¿Qué nos dicen los datos?</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico muestra dos características importantes.</p>
<p>La primera es una <strong>tendencia general positiva</strong>. Los valores máximos aumentan a lo largo de los años: aproximadamente 81.000 dólares en 2014, 76.000 en 2015, 97.000 en 2016 y 118.000 en 2017.</p>
<p>El hecho de que 2015 presente un máximo algo inferior al de 2014 no contradice necesariamente una tendencia creciente. Lo importante es observar el comportamiento general de la serie y no un único año aislado.</p>
<p>La segunda característica es una <strong>variabilidad mensual considerable</strong>.</p>
<p>Las ventas suelen alcanzar valores elevados hacia el final del año, especialmente en noviembre y diciembre, mientras que enero y febrero presentan frecuentemente niveles mucho menores.</p>
<p>Por ejemplo, en 2017 las ventas alcanzaron aproximadamente 118.448 dólares en noviembre, pero fueron de apenas 20.301 dólares en febrero.</p>
<p>Esto nos deja una primera conclusión:</p>
<blockquote class="blockquote">
<p><strong>El negocio parece crecer a lo largo del tiempo, pero ese crecimiento convive con una importante variación entre meses.</strong></p>
</blockquote>
<p>Esta observación será fundamental para nuestro pronóstico.</p>
</section>
</section>
<section id="construir-un-modelo-temporal-sencillo" class="level1">
<h1>4. Construir un modelo temporal sencillo</h1>
<p>Para transformar el tiempo en una variable que pueda utilizar nuestro modelo vamos a asignar un número consecutivo a cada mes.</p>
<p>Así:</p>
<ul>
<li>enero de 2014 corresponde al tiempo 1;</li>
<li>febrero de 2014 al tiempo 2;</li>
<li>…</li>
<li>diciembre de 2017 corresponde al tiempo 48.</li>
</ul>
<p>El modelo que construiremos es deliberadamente sencillo:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>modelo_ventas <span class="ot">&lt;-</span> <span class="fu">stan_glm</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  Sales <span class="sc">~</span> Tiempo,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> ventas_mensuales,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">gaussian</span>(),</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">chains =</span> <span class="dv">2</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">iter =</span> <span class="dv">1000</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed =</span> <span class="dv">1234</span>,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">refresh =</span> <span class="dv">0</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>La idea es muy intuitiva.</p>
<p>Le estamos preguntando al modelo:</p>
<blockquote class="blockquote">
<p><strong>Si las ventas han seguido determinada trayectoria histórica, ¿qué valores de ventas son compatibles con esa trayectoria y con la variabilidad observada?</strong></p>
</blockquote>
<p>El modelo estima dos componentes principales:</p>
<ol type="1">
<li>un punto de partida;</li>
<li>una variación asociada con cada mes adicional.</li>
</ol>
<p>Los resultados fueron:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Parámetro</th>
<th style="text-align: right;">Mediana</th>
<th style="text-align: right;">MAD_SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercepto</td>
<td style="text-align: right;">25.527,6</td>
<td style="text-align: right;">6.628,1</td>
</tr>
<tr class="even">
<td>Tiempo</td>
<td style="text-align: right;">905,7</td>
<td style="text-align: right;">227,1</td>
</tr>
<tr class="odd">
<td>Sigma</td>
<td style="text-align: right;">22.123,6</td>
<td style="text-align: right;">2.117,2</td>
</tr>
</tbody>
</table>
<section id="el-punto-de-partida" class="level2">
<h2 class="anchored" data-anchor-id="el-punto-de-partida">El punto de partida</h2>
<p>El intercepto tiene una mediana posterior de aproximadamente <strong>25.528 dólares</strong>.</p>
<p>Pero debemos tener cuidado con su interpretación.</p>
<p>Nuestro primer mes observado es el mes 1, no el mes 0. Por tanto, no debemos decir que antes de que comenzara el negocio las ventas fueron realmente de 25.528 dólares.</p>
<p>El intercepto representa el valor que el modelo estima matemáticamente cuando <code>Tiempo = 0</code>.</p>
<p>Es, por tanto, un <strong>punto de referencia del modelo</strong>, no una observación histórica.</p>
</section>
<section id="el-efecto-del-tiempo" class="level2">
<h2 class="anchored" data-anchor-id="el-efecto-del-tiempo">El efecto del tiempo</h2>
<p>El parámetro más interesante para nuestra pregunta es <code>Tiempo</code>.</p>
<p>Su media posterior es de aproximadamente <strong>902 dólares</strong>, con un intervalo central del 80% entre <strong>586 y 1.212 dólares</strong>.</p>
<p>En términos empresariales podemos interpretarlo de la siguiente manera:</p>
<blockquote class="blockquote">
<p><strong>Según el modelo, cada mes adicional está asociado, en promedio, con alrededor de 900 dólares adicionales de ventas.</strong></p>
</blockquote>
<p>Existe incertidumbre alrededor de esta estimación. El modelo no afirma que exactamente 900 dólares vayan a agregarse cada mes.</p>
<p>De hecho, el 80% de los valores posteriores considerados se encuentra aproximadamente entre 586 y 1.212 dólares.</p>
<p>Esta es una de las ventajas de pensar de manera bayesiana: no tenemos solamente un número, sino una distribución de valores plausibles para ese número.</p>
</section>
<section id="qué-representa-sigma" class="level2">
<h2 class="anchored" data-anchor-id="qué-representa-sigma">¿Qué representa sigma?</h2>
<p>El parámetro <code>sigma</code> tiene una mediana posterior de aproximadamente <strong>22.124 dólares</strong>.</p>
<p>En términos sencillos, representa la variabilidad de las ventas mensuales que el modelo no consigue explicar únicamente mediante el paso del tiempo.</p>
<p>El 80% de los valores posteriores para <code>sigma</code> está aproximadamente entre <strong>19.471 y 25.656 dólares</strong>.</p>
<p>Esto es importante.</p>
<p>Aunque exista una tendencia creciente, el tiempo por sí solo está lejos de explicar perfectamente las ventas.</p>
<p>Hay otros factores que afectan las ventas mensuales: estacionalidad, promociones, composición de productos, clientes, campañas comerciales y muchos otros elementos que nuestro modelo sencillo no incluye.</p>
<p>Por eso, una buena predicción debe conservar esa incertidumbre.</p>
</section>
</section>
<section id="qué-podría-ocurrir-el-próximo-mes" class="level1">
<h1>5. ¿Qué podría ocurrir el próximo mes?</h1>
<p>Tenemos 48 meses en nuestros datos.</p>
<p>El siguiente período será, por tanto, el <strong>mes 49</strong>, correspondiente a enero de 2018.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(ventas_mensuales<span class="sc">$</span>Tiempo)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>El resultado es 48.</p>
<p>Creamos entonces una observación para el siguiente período:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>proximo_mes <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Tiempo =</span> <span class="fu">max</span>(ventas_mensuales<span class="sc">$</span>Tiempo) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>proximo_mes</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  Tiempo
   &lt;dbl&gt;
1     49</code></pre>
</div>
</div>
<p>El modelo puede utilizar esta nueva observación para generar no una única predicción, sino muchos escenarios posibles.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>predicciones <span class="ot">&lt;-</span> <span class="fu">posterior_predict</span>(</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  modelo_ventas,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">newdata =</span> proximo_mes</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Los resultados obtenidos fueron:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Medida</th>
<th style="text-align: right;">Ventas</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mínimo</td>
<td style="text-align: right;">-3.543</td>
</tr>
<tr class="even">
<td>Primer cuartil</td>
<td style="text-align: right;">54.982</td>
</tr>
<tr class="odd">
<td>Mediana</td>
<td style="text-align: right;">69.970</td>
</tr>
<tr class="even">
<td>Media</td>
<td style="text-align: right;">70.380</td>
</tr>
<tr class="odd">
<td>Tercer cuartil</td>
<td style="text-align: right;">84.743</td>
</tr>
<tr class="even">
<td>Máximo</td>
<td style="text-align: right;">144.821</td>
</tr>
</tbody>
</table>
<p>La primera lectura podría ser:</p>
<blockquote class="blockquote">
<p><strong>El escenario central para enero de 2018 se encuentra alrededor de 70.000 dólares de ventas.</strong></p>
</blockquote>
<p>Pero hay algo todavía más interesante.</p>
<p>El modelo no está diciendo simplemente “las ventas serán 70.000 dólares”.</p>
<p>Está generando una distribución de escenarios.</p>
</section>
<section id="el-futuro-como-una-distribución-de-escenarios" class="level1">
<h1>6. El futuro como una distribución de escenarios</h1>
<p>Podemos visualizar esas predicciones:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La distribución se concentra alrededor de los <strong>70.000 dólares</strong>, aunque existe una dispersión considerable.</p>
<p>La mediana es aproximadamente 69.970 dólares y la media 70.380 dólares. Que ambas cifras sean bastante similares indica que el centro de la distribución se encuentra aproximadamente en esa zona.</p>
<p>También observamos una cola hacia valores considerablemente mayores.</p>
<p>Pero aparece algo extraño: algunos valores de la simulación son negativos.</p>
<section id="puede-una-empresa-tener-ventas-negativas" class="level2">
<h2 class="anchored" data-anchor-id="puede-una-empresa-tener-ventas-negativas">¿Puede una empresa tener ventas negativas?</h2>
<p>No.</p>
<p>Y precisamente aquí aparece una lección metodológica muy importante.</p>
<p>Utilizamos una distribución <strong>gaussiana</strong> para modelar las ventas. La distribución normal tiene una característica matemática: puede generar valores por debajo de cero.</p>
<p>El modelo no sabe que las ventas reales no pueden ser negativas.</p>
<p>Por eso aparecen algunos valores como -3.543 dólares.</p>
<p>Esto <strong>no significa que estemos pronosticando realmente ventas negativas</strong>.</p>
<p>Significa que nuestro modelo es una aproximación sencilla y que la distribución elegida no incorpora explícitamente la restricción de que las ventas deben ser positivas.</p>
<p>Este detalle no invalida automáticamente el análisis, especialmente porque los valores negativos son muy pocos y están muy alejados del centro de la distribución. Pero sí nos recuerda algo fundamental:</p>
<blockquote class="blockquote">
<p><strong>Un modelo puede producir resultados matemáticamente válidos que no sean completamente adecuados para el problema de negocio.</strong></p>
</blockquote>
<p>En un análisis más avanzado podríamos utilizar una especificación que respete mejor la naturaleza positiva de las ventas.</p>
<p>Para esta entrada, sin embargo, nos interesa especialmente aprender la lógica del pronóstico bayesiano: <strong>el futuro se representa mediante una distribución de escenarios y no mediante una única cifra.</strong></p>
</section>
</section>
<section id="el-intervalo-predictivo-cuánto-podría-variar-el-futuro" class="level1">
<h1>7. El intervalo predictivo: cuánto podría variar el futuro</h1>
<p>Podemos resumir la distribución utilizando tres cuantiles:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>intervalo_predictivo <span class="ot">&lt;-</span> <span class="fu">quantile</span>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  predicciones,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Obtuvimos:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Percentil</th>
<th style="text-align: right;">Ventas</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2,5%</td>
<td style="text-align: right;">24.265,87</td>
</tr>
<tr class="even">
<td>50%</td>
<td style="text-align: right;">69.969,77</td>
</tr>
<tr class="odd">
<td>97,5%</td>
<td style="text-align: right;">117.236,26</td>
</tr>
</tbody>
</table>
<p>Por tanto, el intervalo predictivo central del 95% se encuentra aproximadamente entre:</p>
<p><strong>24.266 y 117.236 dólares.</strong></p>
<p>La mediana es de aproximadamente <strong>69.970 dólares</strong>.</p>
<p>Esto nos proporciona una información mucho más útil que decir simplemente “esperamos vender 70.000 dólares”.</p>
<p>Podemos plantearlo así:</p>
<blockquote class="blockquote">
<p><strong>El escenario central para enero de 2018 se sitúa alrededor de 70.000 dólares, pero los escenarios compatibles con el modelo abarcan aproximadamente desde 24.000 hasta 117.000 dólares.</strong></p>
</blockquote>
<p>Esto no significa que exista una probabilidad de exactamente 95% de que el futuro caiga dentro de ese intervalo bajo cualquier interpretación posible. Se trata de un <strong>intervalo predictivo generado por el modelo</strong>, condicionado a los datos, supuestos y estructura que hemos utilizado.</p>
<p>La diferencia es importante: el intervalo refleja tanto la incertidumbre sobre los parámetros como la variabilidad de una futura observación.</p>
</section>
<section id="el-pronóstico-junto-a-la-historia" class="level1">
<h1>8. El pronóstico junto a la historia</h1>
<p>Finalmente podemos colocar el escenario central y su intervalo junto a las ventas históricas.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico resume visualmente todo nuestro análisis.</p>
<p>La serie histórica muestra una tendencia general creciente, pero también una importante variabilidad mensual y un comportamiento estacional aparente, con ventas generalmente mayores hacia el final de los años.</p>
<p>El punto del extremo derecho representa la <strong>mediana predictiva</strong>, cercana a 70.000 dólares.</p>
<p>La barra vertical representa el intervalo predictivo del 95%, aproximadamente entre <strong>24.000 y 117.000 dólares</strong>.</p>
<p>Por tanto, la información que recibe quien debe tomar una decisión es mucho más rica que una única cifra.</p>
</section>
<section id="qué-decisión-empresarial-podemos-tomar" class="level1">
<h1>9. ¿Qué decisión empresarial podemos tomar?</h1>
<p>Supongamos que debemos planificar enero de 2018.</p>
<p>Una respuesta poco cuidadosa sería:</p>
<blockquote class="blockquote">
<p>“Las ventas serán de aproximadamente 70.000 dólares.”</p>
</blockquote>
<p>Una respuesta más útil sería:</p>
<blockquote class="blockquote">
<p>“El escenario central se encuentra alrededor de 70.000 dólares, pero existe una incertidumbre considerable. Bajo nuestro modelo, un intervalo predictivo del 95% se extiende aproximadamente desde 24.000 hasta 117.000 dólares.”</p>
</blockquote>
<p>La segunda respuesta permite pensar en escenarios.</p>
<p>Por ejemplo:</p>
<ul>
<li><strong>Escenario central:</strong> alrededor de 70.000 dólares.</li>
<li><strong>Escenario inferior:</strong> ventas cercanas a 24.000 dólares.</li>
<li><strong>Escenario superior:</strong> ventas cercanas a 117.000 dólares.</li>
</ul>
<p>La empresa puede entonces preguntarse qué decisiones son robustas frente a esos escenarios.</p>
<p>Si estamos planificando inventario, podríamos evitar comprar exactamente la cantidad correspondiente al escenario central si el costo de quedarse sin inventario es muy alto.</p>
<p>Si estamos planificando personal, podríamos evaluar qué capacidad necesitamos si las ventas se acercan al escenario superior.</p>
<p>Si estamos planificando liquidez, podríamos estudiar qué ocurre si las ventas se encuentran considerablemente por debajo del escenario central.</p>
<p>El pronóstico bayesiano no toma la decisión por nosotros.</p>
<p>Nos ayuda a <strong>tomar decisiones conscientes de la incertidumbre</strong>.</p>
</section>
<section id="una-reflexión-bayesiana" class="level1">
<h1>10. Una reflexión bayesiana</h1>
<p>Este ejercicio muestra una diferencia fundamental entre predecir y pronosticar.</p>
<p>Un pronóstico ingenuo intenta producir una cifra:</p>
<blockquote class="blockquote">
<p><strong>“Las ventas serán X.”</strong></p>
</blockquote>
<p>Un enfoque probabilístico pregunta:</p>
<blockquote class="blockquote">
<p><strong>“¿Qué valores de ventas son plausibles y cuánta incertidumbre existe alrededor de ellos?”</strong></p>
</blockquote>
<p>Nuestro modelo estima que existe una trayectoria creciente de las ventas. Pero también reconoce que la variabilidad mensual es considerable.</p>
<p>Por eso el resultado final no es una cifra aislada.</p>
<p>Es una distribución.</p>
<p>Y esa distribución contiene información empresarial.</p>
<p>La mediana nos proporciona un escenario central.</p>
<p>Los cuantiles nos permiten comprender la amplitud de escenarios plausibles.</p>
<p>La dispersión nos recuerda que una tendencia histórica no elimina la incertidumbre.</p>
<p>Incluso la aparición de valores negativos en la simulación nos proporciona una enseñanza: <strong>los modelos deben evaluarse también desde el punto de vista del problema que intentan representar</strong>.</p>
<p>En este caso, la regresión gaussiana es suficientemente sencilla para introducir el concepto, pero tiene una limitación evidente: no conoce la restricción de que las ventas deben ser positivas.</p>
<p>Esto abre la puerta a análisis posteriores en los que podamos construir modelos temporales más adecuados.</p>
<section id="la-idea-que-debemos-conservar" class="level2">
<h2 class="anchored" data-anchor-id="la-idea-que-debemos-conservar">La idea que debemos conservar</h2>
<blockquote class="blockquote">
<p><strong>Pronosticar no significa conocer el futuro. Significa construir una representación explícita de lo que creemos que podría ocurrir y de cuánto podemos equivocarnos.</strong></p>
</blockquote>
<p>En Business Analytics, esa diferencia puede ser más importante que el pronóstico puntual.</p>
</section>
</section>
<section id="conclusiones" class="level1">
<h1>11. Conclusiones</h1>
<p>A partir de los datos de Superstore encontramos una trayectoria general creciente de las ventas durante los cuatro años analizados, acompañada de una importante variabilidad mensual.</p>
<p>El modelo bayesiano estimó una asociación promedio de aproximadamente <strong>900 dólares adicionales de ventas por cada mes</strong> de avance temporal, aunque existe incertidumbre alrededor de esa estimación.</p>
<p>Para el mes 49, correspondiente a enero de 2018, la distribución predictiva se concentró alrededor de <strong>70.000 dólares</strong>.</p>
<p>Sin embargo, el escenario central no debe confundirse con una certeza.</p>
<p>El intervalo predictivo del 95% se extendió aproximadamente entre <strong>24.266 y 117.236 dólares</strong>.</p>
<p>La principal enseñanza es, por tanto, sencilla:</p>
<p><strong>Una buena planificación no necesita que conozcamos exactamente el futuro. Necesita que comprendamos los escenarios plausibles y la incertidumbre que los acompaña.</strong></p>
<p>Y ese es precisamente uno de los aportes más útiles del razonamiento bayesiano al Business Analytics.</p>
</section>
<section id="apéndice-código-completo" class="level1">
<h1>Apéndice — Código completo</h1>
<p>A continuación se presenta el código utilizado en el análisis en el mismo orden en que fue ejecutado.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar las librerías necesarias para el análisis del dataset</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rstanarm)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(posterior)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(bayesplot)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Evitar la notación científica</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar la tabla de superstores sales</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>superstore <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"/kaggle/input/datasets /store3-6/superstore_sales.csv"</span>,</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">guess_max =</span> <span class="dv">10000</span>,</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Comprobar estructura del dataset</span></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(superstore)</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir Order Date al formato de fecha</span></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>superstore <span class="ot">&lt;-</span> superstore <span class="sc">|&gt;</span></span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">Order_Date =</span> <span class="fu">mdy</span>(<span class="st">`</span><span class="at">Order Date</span><span class="st">`</span>)</span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Comprobar que la transformación funcionó</span></span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(superstore<span class="sc">$</span>Order_Date)</span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Conocer cuántos valores faltantes hay en Order_Date</span></span>
<span id="cb15-38"><a href="#cb15-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-39"><a href="#cb15-39" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(superstore<span class="sc">$</span>Order_Date))</span>
<span id="cb15-40"><a href="#cb15-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-41"><a href="#cb15-41" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar por fechas de las ventas</span></span>
<span id="cb15-42"><a href="#cb15-42" aria-hidden="true" tabindex="-1"></a><span class="co"># Agrupar por mes y resumir por ventas totales</span></span>
<span id="cb15-43"><a href="#cb15-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-44"><a href="#cb15-44" aria-hidden="true" tabindex="-1"></a>ventas_mensuales <span class="ot">&lt;-</span> superstore <span class="sc">|&gt;</span></span>
<span id="cb15-45"><a href="#cb15-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Order_Date)) <span class="sc">|&gt;</span></span>
<span id="cb15-46"><a href="#cb15-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb15-47"><a href="#cb15-47" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mes =</span> <span class="fu">floor_date</span>(Order_Date, <span class="at">unit =</span> <span class="st">"month"</span>)</span>
<span id="cb15-48"><a href="#cb15-48" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb15-49"><a href="#cb15-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Mes) <span class="sc">|&gt;</span></span>
<span id="cb15-50"><a href="#cb15-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb15-51"><a href="#cb15-51" aria-hidden="true" tabindex="-1"></a>    <span class="at">Sales =</span> <span class="fu">sum</span>(Sales, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb15-52"><a href="#cb15-52" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb15-53"><a href="#cb15-53" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb15-54"><a href="#cb15-54" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Mes)</span>
<span id="cb15-55"><a href="#cb15-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-56"><a href="#cb15-56" aria-hidden="true" tabindex="-1"></a>ventas_mensuales</span>
<span id="cb15-57"><a href="#cb15-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-58"><a href="#cb15-58" aria-hidden="true" tabindex="-1"></a><span class="co"># Conocer la evolución mensual de las ventas</span></span>
<span id="cb15-59"><a href="#cb15-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-60"><a href="#cb15-60" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb15-61"><a href="#cb15-61" aria-hidden="true" tabindex="-1"></a>  ventas_mensuales,</span>
<span id="cb15-62"><a href="#cb15-62" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb15-63"><a href="#cb15-63" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> Mes,</span>
<span id="cb15-64"><a href="#cb15-64" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> Sales</span>
<span id="cb15-65"><a href="#cb15-65" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb15-66"><a href="#cb15-66" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb15-67"><a href="#cb15-67" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb15-68"><a href="#cb15-68" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb15-69"><a href="#cb15-69" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-70"><a href="#cb15-70" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Ventas mensuales de Superstore"</span>,</span>
<span id="cb15-71"><a href="#cb15-71" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Enero de 2014 a diciembre de 2017"</span>,</span>
<span id="cb15-72"><a href="#cb15-72" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Mes"</span>,</span>
<span id="cb15-73"><a href="#cb15-73" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Ventas"</span></span>
<span id="cb15-74"><a href="#cb15-74" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-75"><a href="#cb15-75" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb15-76"><a href="#cb15-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-77"><a href="#cb15-77" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear una variable que asigne un número</span></span>
<span id="cb15-78"><a href="#cb15-78" aria-hidden="true" tabindex="-1"></a><span class="co"># ordenado a cada mes</span></span>
<span id="cb15-79"><a href="#cb15-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-80"><a href="#cb15-80" aria-hidden="true" tabindex="-1"></a>ventas_mensuales <span class="ot">&lt;-</span> ventas_mensuales <span class="sc">|&gt;</span></span>
<span id="cb15-81"><a href="#cb15-81" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb15-82"><a href="#cb15-82" aria-hidden="true" tabindex="-1"></a>    <span class="at">Tiempo =</span> <span class="fu">row_number</span>()</span>
<span id="cb15-83"><a href="#cb15-83" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb15-84"><a href="#cb15-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-85"><a href="#cb15-85" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear modelo que utilice el paso del tiempo como una forma</span></span>
<span id="cb15-86"><a href="#cb15-86" aria-hidden="true" tabindex="-1"></a><span class="co"># de representar la trayectoria histórica y proyectarla hacia el futuro</span></span>
<span id="cb15-87"><a href="#cb15-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-88"><a href="#cb15-88" aria-hidden="true" tabindex="-1"></a>modelo_ventas <span class="ot">&lt;-</span> <span class="fu">stan_glm</span>(</span>
<span id="cb15-89"><a href="#cb15-89" aria-hidden="true" tabindex="-1"></a>  Sales <span class="sc">~</span> Tiempo,</span>
<span id="cb15-90"><a href="#cb15-90" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> ventas_mensuales,</span>
<span id="cb15-91"><a href="#cb15-91" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">gaussian</span>(),</span>
<span id="cb15-92"><a href="#cb15-92" aria-hidden="true" tabindex="-1"></a>  <span class="at">chains =</span> <span class="dv">2</span>,</span>
<span id="cb15-93"><a href="#cb15-93" aria-hidden="true" tabindex="-1"></a>  <span class="at">iter =</span> <span class="dv">1000</span>,</span>
<span id="cb15-94"><a href="#cb15-94" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed =</span> <span class="dv">1234</span>,</span>
<span id="cb15-95"><a href="#cb15-95" aria-hidden="true" tabindex="-1"></a>  <span class="at">refresh =</span> <span class="dv">0</span></span>
<span id="cb15-96"><a href="#cb15-96" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-97"><a href="#cb15-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-98"><a href="#cb15-98" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(modelo_ventas)</span>
<span id="cb15-99"><a href="#cb15-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-100"><a href="#cb15-100" aria-hidden="true" tabindex="-1"></a><span class="co"># Resumir los resultados del modelo en una tabla</span></span>
<span id="cb15-101"><a href="#cb15-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-102"><a href="#cb15-102" aria-hidden="true" tabindex="-1"></a>resumen_modelo <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">summary</span>(modelo_ventas))</span>
<span id="cb15-103"><a href="#cb15-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-104"><a href="#cb15-104" aria-hidden="true" tabindex="-1"></a>resumen_modelo</span>
<span id="cb15-105"><a href="#cb15-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-106"><a href="#cb15-106" aria-hidden="true" tabindex="-1"></a><span class="co"># Conocer la cantidad de meses que hay en la tabla</span></span>
<span id="cb15-107"><a href="#cb15-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-108"><a href="#cb15-108" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(ventas_mensuales<span class="sc">$</span>Tiempo)</span>
<span id="cb15-109"><a href="#cb15-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-110"><a href="#cb15-110" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear una tabla para el próximo mes</span></span>
<span id="cb15-111"><a href="#cb15-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-112"><a href="#cb15-112" aria-hidden="true" tabindex="-1"></a>proximo_mes <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb15-113"><a href="#cb15-113" aria-hidden="true" tabindex="-1"></a>  <span class="at">Tiempo =</span> <span class="fu">max</span>(ventas_mensuales<span class="sc">$</span>Tiempo) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb15-114"><a href="#cb15-114" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-115"><a href="#cb15-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-116"><a href="#cb15-116" aria-hidden="true" tabindex="-1"></a>proximo_mes</span>
<span id="cb15-117"><a href="#cb15-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-118"><a href="#cb15-118" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear una distribución de predicciones posteriores</span></span>
<span id="cb15-119"><a href="#cb15-119" aria-hidden="true" tabindex="-1"></a><span class="co"># para el próximo mes</span></span>
<span id="cb15-120"><a href="#cb15-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-121"><a href="#cb15-121" aria-hidden="true" tabindex="-1"></a>predicciones <span class="ot">&lt;-</span> <span class="fu">posterior_predict</span>(</span>
<span id="cb15-122"><a href="#cb15-122" aria-hidden="true" tabindex="-1"></a>  modelo_ventas,</span>
<span id="cb15-123"><a href="#cb15-123" aria-hidden="true" tabindex="-1"></a>  <span class="at">newdata =</span> proximo_mes</span>
<span id="cb15-124"><a href="#cb15-124" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-125"><a href="#cb15-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-126"><a href="#cb15-126" aria-hidden="true" tabindex="-1"></a><span class="co"># Resumir las predicciones posteriores</span></span>
<span id="cb15-127"><a href="#cb15-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-128"><a href="#cb15-128" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(predicciones)</span>
<span id="cb15-129"><a href="#cb15-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-130"><a href="#cb15-130" aria-hidden="true" tabindex="-1"></a><span class="co"># Transformar las predicciones posteriores a tabla</span></span>
<span id="cb15-131"><a href="#cb15-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-132"><a href="#cb15-132" aria-hidden="true" tabindex="-1"></a>predicciones_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb15-133"><a href="#cb15-133" aria-hidden="true" tabindex="-1"></a>  <span class="at">Sales =</span> <span class="fu">as.numeric</span>(predicciones)</span>
<span id="cb15-134"><a href="#cb15-134" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-135"><a href="#cb15-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-136"><a href="#cb15-136" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizar la distribución de predicciones posteriores</span></span>
<span id="cb15-137"><a href="#cb15-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-138"><a href="#cb15-138" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb15-139"><a href="#cb15-139" aria-hidden="true" tabindex="-1"></a>  predicciones_df,</span>
<span id="cb15-140"><a href="#cb15-140" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> Sales)</span>
<span id="cb15-141"><a href="#cb15-141" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb15-142"><a href="#cb15-142" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb15-143"><a href="#cb15-143" aria-hidden="true" tabindex="-1"></a>    <span class="at">bins =</span> <span class="dv">40</span></span>
<span id="cb15-144"><a href="#cb15-144" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-145"><a href="#cb15-145" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-146"><a href="#cb15-146" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Escenarios plausibles para las ventas del próximo mes"</span>,</span>
<span id="cb15-147"><a href="#cb15-147" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Distribución predictiva posterior"</span>,</span>
<span id="cb15-148"><a href="#cb15-148" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Ventas previstas"</span>,</span>
<span id="cb15-149"><a href="#cb15-149" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Frecuencia"</span></span>
<span id="cb15-150"><a href="#cb15-150" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-151"><a href="#cb15-151" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb15-152"><a href="#cb15-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-153"><a href="#cb15-153" aria-hidden="true" tabindex="-1"></a><span class="co"># Conocer las predicciones posteriores de los cuantiles</span></span>
<span id="cb15-154"><a href="#cb15-154" aria-hidden="true" tabindex="-1"></a><span class="co"># 2.5%, 50% y 97.5%</span></span>
<span id="cb15-155"><a href="#cb15-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-156"><a href="#cb15-156" aria-hidden="true" tabindex="-1"></a>intervalo_predictivo <span class="ot">&lt;-</span> <span class="fu">quantile</span>(</span>
<span id="cb15-157"><a href="#cb15-157" aria-hidden="true" tabindex="-1"></a>  predicciones,</span>
<span id="cb15-158"><a href="#cb15-158" aria-hidden="true" tabindex="-1"></a>  <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>)</span>
<span id="cb15-159"><a href="#cb15-159" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-160"><a href="#cb15-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-161"><a href="#cb15-161" aria-hidden="true" tabindex="-1"></a>intervalo_predictivo</span>
<span id="cb15-162"><a href="#cb15-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-163"><a href="#cb15-163" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear una tabla para el próximo mes</span></span>
<span id="cb15-164"><a href="#cb15-164" aria-hidden="true" tabindex="-1"></a><span class="co"># con los cuantiles 2.5%, 50% y 97.5%</span></span>
<span id="cb15-165"><a href="#cb15-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-166"><a href="#cb15-166" aria-hidden="true" tabindex="-1"></a>intervalo_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb15-167"><a href="#cb15-167" aria-hidden="true" tabindex="-1"></a>  <span class="at">Mes =</span> <span class="fu">as.Date</span>(<span class="st">"2018-01-01"</span>),</span>
<span id="cb15-168"><a href="#cb15-168" aria-hidden="true" tabindex="-1"></a>  <span class="at">Mediana =</span> <span class="fu">as.numeric</span>(intervalo_predictivo[<span class="dv">2</span>]),</span>
<span id="cb15-169"><a href="#cb15-169" aria-hidden="true" tabindex="-1"></a>  <span class="at">Inferior =</span> <span class="fu">as.numeric</span>(intervalo_predictivo[<span class="dv">1</span>]),</span>
<span id="cb15-170"><a href="#cb15-170" aria-hidden="true" tabindex="-1"></a>  <span class="at">Superior =</span> <span class="fu">as.numeric</span>(intervalo_predictivo[<span class="dv">3</span>])</span>
<span id="cb15-171"><a href="#cb15-171" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-172"><a href="#cb15-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-173"><a href="#cb15-173" aria-hidden="true" tabindex="-1"></a>intervalo_df</span>
<span id="cb15-174"><a href="#cb15-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-175"><a href="#cb15-175" aria-hidden="true" tabindex="-1"></a><span class="co"># Colocar la predicción del próximo mes junto a las</span></span>
<span id="cb15-176"><a href="#cb15-176" aria-hidden="true" tabindex="-1"></a><span class="co"># ventas históricas</span></span>
<span id="cb15-177"><a href="#cb15-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-178"><a href="#cb15-178" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb15-179"><a href="#cb15-179" aria-hidden="true" tabindex="-1"></a>  ventas_mensuales,</span>
<span id="cb15-180"><a href="#cb15-180" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> Mes, <span class="at">y =</span> Sales)</span>
<span id="cb15-181"><a href="#cb15-181" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb15-182"><a href="#cb15-182" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb15-183"><a href="#cb15-183" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb15-184"><a href="#cb15-184" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(</span>
<span id="cb15-185"><a href="#cb15-185" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> intervalo_df,</span>
<span id="cb15-186"><a href="#cb15-186" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> Mes, <span class="at">y =</span> Mediana),</span>
<span id="cb15-187"><a href="#cb15-187" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">4</span></span>
<span id="cb15-188"><a href="#cb15-188" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-189"><a href="#cb15-189" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(</span>
<span id="cb15-190"><a href="#cb15-190" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> intervalo_df,</span>
<span id="cb15-191"><a href="#cb15-191" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(</span>
<span id="cb15-192"><a href="#cb15-192" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> Mes,</span>
<span id="cb15-193"><a href="#cb15-193" aria-hidden="true" tabindex="-1"></a>      <span class="at">ymin =</span> Inferior,</span>
<span id="cb15-194"><a href="#cb15-194" aria-hidden="true" tabindex="-1"></a>      <span class="at">ymax =</span> Superior</span>
<span id="cb15-195"><a href="#cb15-195" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb15-196"><a href="#cb15-196" aria-hidden="true" tabindex="-1"></a>    <span class="at">width =</span> <span class="dv">15</span>,</span>
<span id="cb15-197"><a href="#cb15-197" aria-hidden="true" tabindex="-1"></a>    <span class="at">inherit.aes =</span> <span class="cn">FALSE</span></span>
<span id="cb15-198"><a href="#cb15-198" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-199"><a href="#cb15-199" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-200"><a href="#cb15-200" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Ventas históricas y pronóstico para enero de 2018"</span>,</span>
<span id="cb15-201"><a href="#cb15-201" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"La predicción se presenta como un escenario central acompañado de incertidumbre"</span>,</span>
<span id="cb15-202"><a href="#cb15-202" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Mes"</span>,</span>
<span id="cb15-203"><a href="#cb15-203" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Ventas"</span></span>
<span id="cb15-204"><a href="#cb15-204" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-205"><a href="#cb15-205" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>